export class Pattern {
    constructor() {
        this.beats = [
            [
                1,
                8,
                4
            ],
            [],
            [
                3
            ],
            [],
            [
                2,
                6,
                5,
                7
            ],
            [],
            [
                3
            ],
            [],
            [
                3
            ],
            [],
            [
                1,
                8
            ],
            [],
            [
                2,
                7,
                5,
                6
            ],
            [],
            [
                3
            ],
            []
        ]
    }
}